### PR TITLE
outofbounds, display and visibility improvements

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes:
https://github.com/adaptlearning/adapt_framework/issues/1881
https://github.com/adaptlearning/adapt_framework/issues/1873

### CODE REVIEW

**Comment by danielstorey** [comment]
I like checking style attributes first as this avoids unnecessary `getComputedStyle` calls, which was my only concern with my suggestion! I think the logic also needs adding when iterating parents as well though [here](https://github.com/adaptlearning/jquery.onscreen/pull/24/files#diff-ed9b986b1a55a1e622c0eca864596e06L520).

Since the same logic occurs in both places maybe abstracting it slightly to something like this would help:
```
isElementHidden: function(element) {
    var cssHidden = (el.style.display == "none" || el.style.visibility == "hidden");
    if (cssHidden) return true;

    var style = window.getComputedStyle(el, null);
    cssHidden = (style.display == "none" || style.visibility == "hidden");
    return cssHidden;
}
```

**Comment by oliverfoster** [comment]
👍  nice plan

**Comment by oliverfoster** [comment]
hows that?

**Comment by oliverfoster** [comment]
lovely, thanks 👍

**Pull request merged**
