### PR TITLE
Corrected typo in get() function

### PR DESCRIPTION
**Pull request by brian-learningpool**
This was causing errors in IE 11.

### CODE REVIEW

**Comment by oliverfoster** [comment]
what kinda errors? this is needed for ie8 debugging. otherwise the function has no name (gasp!)

**Comment by oliverfoster** [comment]
there's nothing wrong with the syntax, it just looks a bit weird. a double name. one is the function name the other is the object property name.

**Comment by moloko** [comment]
> there's nothing wrong with the syntax, it just looks a bit weird. a double name. one is the function name the other is the object property name.

oh yeah I remember you explaining this to me at one point

**Comment by brian-learningpool** [comment]
Intermittent JS errors could be caused by my setup, ngrok, IE 11 VM or the content loaded in the frame itself.

**Pull request closed without merging**
